### ISSUE TITLE
Slow on multi-word matches

### ISSUE THREAD

**Issue by elsehow** [princejwesley/extractjs#2]
Hi, me again

This executes very slowly for me - was wondering if it's reproducable

``` javascript
var matcher = extractor(
  "you can {command} to go to {place}", 
  "you can fall through the book to go to a quiet island dock")
```

**Comment by princejwesley** [comment]
I'll test it

**Comment by princejwesley** [comment]
@elsehow Sorry, please test and confirm the fix.

**Comment by elsehow** [comment]
@princejwesley fixed! thank you very much for fixing all these issues so quickly.
